name: Deploy Lambda

on:
  push:
    branches: [main]   # ´runs after PR is merged into main

permissions:
  id-token: write   # required for OIDC
  contents: read  # Required to check out the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # match whatever runtime your Lambda uses

      # in your GitHub Actions workflow, before `chalice deploy`
      # - name: Download Bitwarden CLI
      #   run: |
      #     mkdir -p vendor
      #     unzip bw.zip -d vendor/
      #     chmod +x vendor/bw

      - name: Install Bitwarden CLI via npm
        run: |
          mkdir -p vendor
          npm install @bitwarden/cli --prefix ./bw-install
          cp ./bw-install/node_modules/.bin/bw vendor/bw
          chmod +x vendor/bw

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::588146318465:role/TechOps-github-actions-lambda-deploy
          aws-region: us-west-2

      - name: Determine stage
        id: stage
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "stage=${{ github.event.inputs.stage }}" >> $GITHUB_OUTPUT
          else
            echo "stage=prod" >> $GITHUB_OUTPUT
          fi

      - name: Prepare requirements.txt for Chalice
        run: |
          if [ "${{ steps.stage.outputs.stage }}" = "prod" ]; then
            cp requirements-PROD.txt requirements.txt
          else
            cp requirements-TEST.txt requirements.txt
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ "${{ steps.stage.outputs.stage }}" = "prod" ]; then
            pip install -r requirements-PROD.txt
          else
            pip install -r requirements-TEST.txt
          fi
          pip install chalice


      - name: Deploy with Chalice
        env:
          BW_PATH: ${{ github.workspace }}/bw-install/node_modules/@bitwarden/cli/build/bw.js
        run: |
          chmod +x "$BW_PATH"
          run: chalice deploy --stage ${{ steps.stage.outputs.stage }}
