name: Deploy Lambda

on:
  push:
    branches: [main]   # ´runs after PR is merged into main

permissions:
  id-token: write   # required for OIDC
  contents: read  # Required to check out the repository

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # match whatever runtime your Lambda uses

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::588146318465:role/TechOps-github-actions-lambda-deploy
          aws-region: us-west-2

      # - name: Install dependencies into package folder
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements-PROD.txt -t package/

      # - name: Copy source code into package
      #   run: |
      #     cp -r *.py package/   # adjust if your code lives in a subfolder, e.g. src/

      # - name: Create build directory and install dependencies
      #   run: |
      #     mkdir -p build
      #     pip install -r requirements-PROD.txt -t build/

      # - name: Copy application code into build directory
      #   run: |
      #     cp app.py build/
      #     cp -r chalicelib build/

      # - name: Zip package
      #   run: |
      #     cd package
      #     zip -r ../function.zip .

      # - name: Deploy to Lambda
      #   uses: aws-actions/aws-lambda-deploy@v1
      #   with:
      #     function-name: TechOps-bw-create-individual-collection-Index-ScTilHTb5mBn
      #     zip-file: function.zip

      # - name: Deploy Lambda Function
      #   uses: aws-actions/aws-lambda-deploy@v1
      #   with:
      #     function-name: TechOps-bw-create-individual-collection-Index-ScTilHTb5mBn
      #     code-artifacts-dir: build

      - name: Determine stage
        id: stage
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "stage=${{ github.event.inputs.stage }}" >> $GITHUB_OUTPUT
          else
            echo "stage=prod" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ "${{ steps.stage.outputs.stage }}" = "prod" ]; then
            pip install -r requirements-PROD.txt
          else
            pip install -r requirements-TEST.txt
          fi
          pip install chalice


      # - name: Deploy with Chalice
      #   run: chalice deploy --stage ${{ steps.stage.outputs.stage }}

      - name: Package with Chalice
        run: chalice package packaged/

      - name: Package with CloudFormation (upload assets to S3)
        run: |
          aws cloudformation package \
            --template-file ./packaged/sam.json \
            --s3-bucket config-safe \
            --s3-prefix cloudformation/OPS/sam-deployments/techops-onboard-bitwarden \
            --output-template-file sam-packaged.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./sam-packaged.yaml \
            --stack-name techops-onboard-bitwarden \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

  # AssumeRoleAndCallIdentity:
  #   runs-on: self-hosted
  #   steps:
  #     # - name: Git clone the repository
  #     #   uses: actions/checkout@v3

  #     - name: Debug OIDC claims
  #       run: |
  #         curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
  #           "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
  #           | jq -r '.value' | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .

  #     - name: configure aws credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::588146318465:role/TechOps-github-actions-lambda-deploy #change to reflect your IAM role’s ARN
  #         aws-region: us-west-2

  #     # Hello from AWS: WhoAmI
  #     - name: Sts GetCallerIdentity
  #       run: |
  #         aws sts get-caller-identity
